### ISSUE TITLE
Storing 1D DataFrame gives Pandas TypeError on retrieval

### ISSUE THREAD

**Issue by cing** [Becksteinlab/MDSynthesis#20]
I'm not exactly sure what's going on here, but I can't store a 1D DataFrame. Retrieving a (10,1) DataFrame gives the error "TypeError: Index(...) must be called with a collection of some kind, None was passed":

```
import mdsynthesis as mds                                                        
import numpy as np                                                               
import pandas as pd                                                              
                                                                                 
s = mds.Sim('marklar')                                                           
s.data.add('test1',pd.DataFrame(np.zeros((1,10))))                                                            
print s.data["test1"]        #Good
                                                    
s.data.add('test2',pd.Series(np.zeros((10,))))                                                                        
print s.data["test2"]        #Good

s.data.add('test3',pd.DataFrame(np.zeros((10,10))))                                                              
print s.data["test3"]        #Good

s.data.add('test4',pd.DataFrame(np.zeros((10,1))))                                                              
print s.data["test4"]        #Not Good
```

I'm pretty sure this is actually a problem with writing the file to disk because the h5 file seems weird:
```
z=pd.HDFStore("test4/pdData.h5", 'r')
>>> z
<class 'pandas.io.pytables.HDFStore'>
File path: pdData.h5
/main            [invalid_HDFStore node: sequence item 0: expected string, numpy.int64 found]
```
Any idea how to fix this?

**Comment by dotsdl** [comment]
This appears to be due to the defaults chosen for ``pandas`` object storage. The ``MDSynthesis.core.persistence.pdDataFile.add_data`` method first tries to store the object with ``data_columns=True``, which will create an index that allows PyTables ``where`` queries to be performed on columns. However, [this is a problem if column names start with numbers](http://pandas.pydata.org/pandas-docs/dev/io.html#notes-caveats), and so the method falls back on not using ``data_columns=True`` if it fails.

This appears to work for all of the DataFrames in this test except for the 1D one. For all of those, an ``AttributeError`` is raised and caught as expected. But for that one, no ``AttributeError`` is raised.

I'll add a band-aid heuristic to catch this corner case, then I'll submit an issue to pandas to hopefully get it resolved there. Thanks for catching this!

**Comment by dotsdl** [comment]
I'm stealing these tests for the unittests, btw. :D

**Comment by dotsdl** [comment]
Hopefully there aren't any other weird corner cases that ``HDFStore`` doesn't catch. Otherwise, we'll just have to work around them.

**Comment by cing** [comment]
Awesome, I just tried it and the issue is certainly resolved. I guess the lesson is to use sensible column names!
