### ISSUE TITLE
renaming universes?

### ISSUE THREAD

**Issue by orbeckst** [Becksteinlab/MDSynthesis#27]
I haven't found a way to rename a universe --- am I missing something? I was looking for 
```python
Sim.universes.rename(old, new)
```
or at least

```python
Sim.universes[new] = Sim.universes[old]
del Sim.universes[old]
```

**Comment by dotsdl** [comment]
Currently, there is no way to directly rename a universe. For now you could do:

s.universes[old]
s.universes.add(new, s.universe.filename, s.universe.trajectory.filenames)
s.universes.resnums(new, s.universe.atoms.resnums)
s.universes[new]
s.selections.copy(old)
s.universes.remove(old)

And this will ensure everything the old universe definition had ends up in the new one, but this is beyond clunky. I aggree this method (``Sim.universes.rename()``) should be added, and I think the other pythonic expression should work, too (once we have #25, it will be almost trivial). I can add the ``__delitem__`` method immediately so that

```python
del Sim.universes[old]
```
works as expected.
