### ISSUE TITLE
Data aggregator doesn't have keys method

### ISSUE THREAD

**Issue by richardjgowers** [Becksteinlab/MDSynthesis#35]
``` python
Sim.selections.keys() # works
Sim.categories.keys() # works

# but
Sim.data.keys() # doesn't work
Sim.universes.keys() # doesn't work

```

If I'm using a dict like object, it makes sense to have a `keys` method for this.  I had a quick look through the code, and it looks like the `data` aggregator is different, but ideally it should behave like the others?  Maybe link `keys` to `data._list`?

**Comment by dotsdl** [comment]
Agreed. Originally I was wary of making aggregators look too much like dicts lest they be expected to behave like dicts in every way, since not every method available for dicts makes sense for these objects. I've since changed my mind, and at least with respect to ``keys``; the other aggregators reflect this, but I missed doing it for ``Data``. I'll add a ``keys`` method to the ``Data`` aggregator.
